version: '3.8'

services:
  backend:
    build: .
    container_name: bible_backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE: config.settings
      - DB_ENGINE: django.db.backends.postgresql
      - DB_NAME: bible_db
      - DB_USER: bible_user
      - DB_PASSWORD: godlovesyou
      - DB_HOST: db
      - DB_PORT: 5432
      - DJANGO_SECRET_KEY: "django-insecure-8m)f=4)en0*zub9f%+tz&oyfe$@)%@t96_c0_g@+=y__h7*!)_"
    depends_on:
      - db

  frontend:
    build: ../j316_front/bible-website
    container_name: bible_frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: bible_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - bible_db_data:/var/lib/postgresql/data
    networks:
      - bible_network

volumes:
  bible_db_data:  # 볼륨 정의

networks:
  bible_network:
    driver: bridge