version: '3.8'

services:
  backend:
    build: .
    container_name: bible_backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db

  frontend:
    build: ../j316_front/bible-website
    container_name: bible_frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: bible_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - bible_db_data:/var/lib/postgresql/data
    networks:
      - bible_network

volumes:
  bible_db_data:  # 볼륨 정의

networks:
  bible_network:
    driver: bridge