version: '3.8'

services:
  backend:
    build: .
    container_name: bible_backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - db

  frontend:
    build: ../frontend/bible-website
    container_name: bible_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: bible_db
    environment:
      POSTGRES_USER: bible_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bible_db
    ports:
      - "5432:5432"